FROM python:3.7.3-alpine3.9
RUN apk --update add build-base mysql-dev bash

ADD src/server/requirements.txt /app/requirements.txt
RUN cd /app && pip install -r requirements.txt
COPY docker/scripts/django/run.sh /run.sh
RUN chmod +x /run.sh

WORKDIR /app

EXPOSE 80
CMD ["/bin/bash", "/run.sh"]
